name       : haskell-monad-unlift
version    : 0.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/monad-unlift-0.2.0/monad-unlift-0.2.0.tar.gz : 4b5e638619e4821918b4ec67aeffb581ab9df23d168fbb72164137009a15ee0f
license    : MIT
component  : programming.haskell
summary    : Typeclasses for providing for unlifting of monad transformers and stacks.
description: |
    Typeclasses for providing for unlifting of monad transformers and stacks.
builddeps  :
    - haskell-cabal-install
    - haskell-constraints
    - haskell-monad-control
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
